//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.08 at 08:58:25 PM MSK 
//


package by.tareltos.webtask.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Objects;


/**
 * <p>Java class for candy complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="candy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}gYearMonth"/>
 *         &lt;element name="energy" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ingredients" type="{http://www.example.com/candies}ingredients"/>
 *         &lt;element name="energyvalue" type="{http://www.example.com/candies}energyvalue"/>
 *         &lt;element name="description" type="{http://www.example.com/candies}validateDescr"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="production" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "candy", propOrder = {
        "date",
        "energy",
        "ingredients",
        "energyvalue",
        "description"
})
@XmlSeeAlso({
        Caramel.class,
        Chocolate.class
})
public class Candy {

    @XmlElement(required = true)
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar date;
    @XmlElement(defaultValue = "200")
    protected double energy;
    @XmlElement(required = true)
    protected Ingredients ingredients;
    @XmlElement(required = true)
    protected Energyvalue energyvalue;
    @XmlElement(required = true)
    protected String description;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;
    @XmlAttribute(name = "production")
    protected String production;

    /**
     * Gets the value of the date property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the energy property.
     */
    public double getEnergy() {
        return energy;
    }

    /**
     * Sets the value of the energy property.
     */
    public void setEnergy(double value) {
        this.energy = value;
    }

    /**
     * Gets the value of the ingredients property.
     *
     * @return possible object is
     * {@link Ingredients }
     */
    public Ingredients getIngredients() {
        return ingredients;
    }

    /**
     * Sets the value of the ingredients property.
     *
     * @param value allowed object is
     *              {@link Ingredients }
     */
    public void setIngredients(Ingredients value) {
        this.ingredients = value;
    }

    /**
     * Gets the value of the energyvalue property.
     *
     * @return possible object is
     * {@link Energyvalue }
     */
    public Energyvalue getEnergyvalue() {
        return energyvalue;
    }

    /**
     * Sets the value of the energyvalue property.
     *
     * @param value allowed object is
     *              {@link Energyvalue }
     */
    public void setEnergyvalue(Energyvalue value) {
        this.energyvalue = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the production property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProduction() {
        return production;
    }

    /**
     * Sets the value of the production property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProduction(String value) {
        this.production = value;
    }

    public void setDefaultEnergy() {
        energy = 200.0;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Candy candy = (Candy) o;
        return Double.compare(candy.energy, energy) == 0 &&
                Objects.equals(date, candy.date) &&
                Objects.equals(ingredients, candy.ingredients) &&
                Objects.equals(energyvalue, candy.energyvalue) &&
                Objects.equals(description, candy.description) &&
                Objects.equals(name, candy.name) &&
                Objects.equals(production, candy.production);
    }

    @Override
    public int hashCode() {

        return Objects.hash(date, energy, ingredients, energyvalue, description, name, production);
    }

    @Override
    public String toString() {
        return "Candy{" +
                "date=" + date +
                ", energy=" + energy +
                ", ingredients=" + ingredients +
                ", energyvalue=" + energyvalue +
                ", description='" + description + '\'' +
                ", name='" + name + '\'' +
                ", production='" + production + '\'' +
                '}';
    }
}
