//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.08 at 08:58:25 PM MSK 
//


package by.tareltos.webtask.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.Objects;


/**
 * <p>Java class for caramel complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="caramel">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/candies}candy">
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Caramel" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "caramel")
public class Caramel
        extends Candy {

    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        if (type == null) {
            return "Caramel";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    @Override
    public String toString() {
        return "Caramel{" +
                "type='" + type + '\'' +
                ", date=" + date +
                ", energy=" + energy +
                ", ingredients=" + ingredients +
                ", energyvalue=" + energyvalue +
                ", description='" + description + '\'' +
                ", name='" + name + '\'' +
                ", production='" + production + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Caramel caramel = (Caramel) o;
        return Objects.equals(type, caramel.type);
    }

    @Override
    public int hashCode() {

        return Objects.hash(type);
    }
}
