//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.23 at 11:28:52 AM AST 
//


package by.tareltos.webtask.entity;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ingredients complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ingredients">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="fructose" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *       &lt;attribute name="chocolatetype">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="white"/>
 *             &lt;enumeration value="black"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ingredients", propOrder = {
    "water",
    "sugar",
    "fructose",
    "vanillin"
})
public class Ingredients {

    protected boolean water;
    protected double sugar;
    protected double fructose;
    protected double vanillin;
    @XmlAttribute(name = "chocolatetype")
    protected String chocolatetype;

    /**
     * Gets the value of the water property.
     * 
     */
    public boolean isWater() {
        return water;
    }

    /**
     * Sets the value of the water property.
     * 
     */
    public void setWater(boolean value) {
        this.water = value;
    }

    /**
     * Gets the value of the sugar property.
     * 
     */
    public double getSugar() {
        return sugar;
    }

    /**
     * Sets the value of the sugar property.
     * 
     */
    public void setSugar(double value) {
        this.sugar = value;
    }

    /**
     * Gets the value of the fructose property.
     * 
     */
    public double getFructose() {
        return fructose;
    }

    /**
     * Sets the value of the fructose property.
     * 
     */
    public void setFructose(double value) {
        this.fructose = value;
    }

    /**
     * Gets the value of the vanillin property.
     * 
     */
    public double getVanillin() {
        return vanillin;
    }

    /**
     * Sets the value of the vanillin property.
     * 
     */
    public void setVanillin(double value) {
        this.vanillin = value;
    }

    /**
     * Gets the value of the chocolatetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChocolatetype() {
        return chocolatetype;
    }

    /**
     * Sets the value of the chocolatetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChocolatetype(String value) {
        this.chocolatetype = value;
    }

}
